name: .NET Core 31 - Push

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    name: Build Code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        #dotnet: ['3.1.100','3.1.101','3.1.200','3.1.301']
    steps:    
    - name: Baixar o Código Fonte
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o dotnetcorewebapp
      
      # Task responsável por efetuar upload do artefato gerado
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: App_${{ matrix.os }}_${{ matrix.dotnet }}
        # A file, directory or wildcard pattern that describes what to upload
        path: dotnetcorewebapp
